merge driver/pmi8998_haptics
Squashed commit of the following:

commit ad2d6c6e6ca44a42f731d6a338bf267283d2c77f
Author: Caleb Connolly <caleb@connolly.tech>
Date:   Sat Apr 17 16:53:34 2021 +0100

    dts: sdm845: beryllium: enable haptics

    Enable the haptics node and set the play rate from downstream.

    Signed-off-by: Caleb Connolly <caleb@connolly.tech>

commit ac8708e3707b7e94b159284d2e1a40bbfc3523af
Author: Caleb Connolly <caleb@connolly.tech>
Date:   Wed Feb 24 13:14:51 2021 +0000

    dts: sdm845: oneplus: enable haptics

    Enable the haptics node and set the play rate from downstream.

    Signed-off-by: Caleb Connolly <caleb@connolly.tech>

commit 81f99854215f3f7c5c0ade3aabe4b60c345d191d
Author: Caleb Connolly <caleb@connolly.tech>
Date:   Thu Jan 28 19:45:25 2021 +0000

    arm64: dts: pmi8998: add pmi8998_haptics

    Add a node for the pmi8998 haptics device.

    Signed-off-by: Caleb Connolly <caleb@connolly.tech>

commit 16898721f66b84497e4277be63e3ce33a4dc7c7d
Author: Caleb Connolly <caleb@connolly.tech>
Date:   Thu Jan 28 19:41:37 2021 +0000

    input: pmi8998_haptics: introduce new haptics driver

    Introduce a haptics driver for the pmi8998 haptics engine used by
    several generations of Qualcomm SoCs (MSM8996 through SDM845).

    Here we only implement a small subset of common operations, advanced
    features like customising the wave pattern, driving the haptics via pwm
    and several other features are either stubbed or left unimplemented for
    now.

    Signed-off-by: Caleb Connolly <caleb@connolly.tech>

commit d434405aaab7d0ebc516b68a8fc4100922d7f5ef
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Apr 11 15:16:13 2021 -0700

    Linux 5.12-rc7

commit 7d900724913cb293620a05c5a3134710db95d0d9
Merge: add6b92660b3 53b74fa990bf
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Apr 11 11:53:36 2021 -0700

    Merge tag 'for-5.12-rc6-tag' of git://git.kernel.org/pub/scm/linux/kernel/git/kdave/linux

    Pull btrfs fix from David Sterba:
     "One more patch that we'd like to get to 5.12 before release.

      It's changing where and how the superblock is stored in the zoned
      mode. It is an on-disk format change but so far there are no
      implications for users as the proper mkfs support hasn't been merged
      and is waiting for the kernel side to settle.

      Until now, the superblocks were derived from the zone index, but zone
      size can differ per device. This is changed to be based on fixed
      offset values, to make it independent of the device zone size.

      The work on that got a bit delayed, we discussed the exact locations
      to support potential device sizes and usecases. (Partially delayed
      also due to my vacation.) Having that in the same release where the
      zoned mode is declared usable is highly desired, there are userspace
      projects that need to be updated to recognize the feature. Pushing
      that to the next release would make things harder to test"

    * tag 'for-5.12-rc6-tag' of git://git.kernel.org/pub/scm/linux/kernel/git/kdave/linux:
      btrfs: zoned: move superblock logging zone location

commit add6b92660b3dca65465d3bd7710b4b1338f34f0
Merge: 06f838e02d3b 6d48b7912cc7
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Apr 11 11:47:03 2021 -0700

    Merge tag 'locking-urgent-2021-04-11' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip

    Pull locking fixlets from Ingo Molnar:
     "Two minor fixes: one for a Clang warning, the other improves an
      ambiguous/confusing kernel log message"

    * tag 'locking-urgent-2021-04-11' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip:
      lockdep: Address clang -Wformat warning printing for %hd
      lockdep: Add a missing initialization hint to the "INFO: Trying to register non-static key" message

commit 06f838e02d3b6e161df08c910e12e8366f1cb465
Merge: 52e44129fba5 632a1c209b87
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Apr 11 11:42:18 2021 -0700

    Merge tag 'x86_urgent_for_v5.12-rc7' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip

    Pull x86 fixes from Borislav Petkov:

     - Fix the vDSO exception handling return path to disable interrupts
       again.

     - A fix for the CE collector to return the proper return values to its
       callers which are used to convey what the collector has done with the
       error address.

    * tag 'x86_urgent_for_v5.12-rc7' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip:
      x86/traps: Correct exc_general_protection() and math_error() return paths
      RAS/CEC: Correct ce_add_elem()'s returned values

commit 52e44129fba5cfc4e351fdb5e45849afc74d9a53
Merge: efc2da9241e6 0760fa3d8f7f
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat Apr 10 12:51:12 2021 -0700

    Merge branch 'for-5.12-fixes' of git://git.kernel.org/pub/scm/linux/kernel/git/dennis/percpu

    Pull percpu fix from Dennis Zhou:
     "This contains a fix for sporadically failing atomic percpu
      allocations.

      I only caught it recently while I was reviewing a new series [1] and
      simultaneously saw reports by btrfs in xfstests [2] and [3].

      In v5.9, memcg accounting was extended to percpu done by adding a
      second type of chunk. I missed an interaction with the free page float
      count used to ensure we can support atomic allocations. If one type of
      chunk has no free pages, but the other has enough to satisfy the free
      page float requirement, we will not repopulate the free pages for the
      former type of chunk. This led to the sporadically failing atomic
      allocations"

    Link: https://lore.kernel.org/linux-mm/20210324190626.564297-1-guro@fb.com/ [1]
    Link: https://lore.kernel.org/linux-mm/20210401185158.3275.409509F4@e16-tech.com/ [2]
    Link: https://lore.kernel.org/linux-mm/CAL3q7H5RNBjCi708GH7jnczAOe0BLnacT9C+OBgA-Dx9jhB6SQ@mail.gmail.com/ [3]

    * 'for-5.12-fixes' of git://git.kernel.org/pub/scm/linux/kernel/git/dennis/percpu:
      percpu: make pcpu_nr_empty_pop_pages per chunk type

commit 53b74fa990bf76f290aa5930abfcf37424a1a865
Author: Naohiro Aota <naohiro.aota@wdc.com>
Date:   Thu Apr 8 17:25:28 2021 +0900

    btrfs: zoned: move superblock logging zone location

    Moves the location of the superblock logging zones. The new locations of
    the logging zones are now determined based on fixed block addresses
    instead of on fixed zone numbers.

    The old placement method based on fixed zone numbers causes problems when
    one needs to inspect a file system image without access to the drive zone
    information. In such case, the super block locations cannot be reliably
    determined as the zone size is unknown. By locating the superblock logging
    zones using fixed addresses, we can scan a dumped file system image without
    the zone information since a super block copy will always be present at or
    after the fixed known locations.

    Introduce the following three pairs of zones containing fixed offset
    locations, regardless of the device zone size.

      - primary superblock: offset   0B (and the following zone)
      - first copy:         offset 512G (and the following zone)
      - Second copy:        offset   4T (4096G, and the following zone)

    If a logging zone is outside of the disk capacity, we do not record the
    superblock copy.

    The first copy position is much larger than for a non-zoned filesystem,
    which is at 64M.  This is to avoid overlapping with the log zones for
    the primary superblock. This higher location is arbitrary but allows
    supporting devices with very large zone sizes, plus some space around in
    between.

    Such large zone size is unrealistic and very unlikely to ever be seen in
    real devices. Currently, SMR disks have a zone size of 256MB, and we are
    expecting ZNS drives to be in the 1-4GB range, so this limit gives us
    room to breathe. For now, we only allow zone sizes up to 8GB. The
    maximum zone size that would still fit in the space is 256G.

    The fixed location addresses are somewhat arbitrary, with the intent of
    maintaining superblock reliability for smaller and larger devices, with
    the preference for the latter. For this reason, there are two superblocks
    under the first 1T. This should cover use cases for physical devices and
    for emulated/device-mapper devices.

    The superblock logging zones are reserved for superblock logging and
    never used for data or metadata blocks. Note that we only reserve the
    two zones per primary/copy actually used for superblock logging. We do
    not reserve the ranges of zones possibly containing superblocks with the
    largest supported zone size (0-16GB, 512G-528GB, 4096G-4112G).

    The zones containing the fixed location offsets used to store
    superblocks on a non-zoned volume are also reserved to avoid confusion.

    Signed-off-by: Naohiro Aota <naohiro.aota@wdc.com>
    Signed-off-by: David Sterba <dsterba@suse.com>

commit 0760fa3d8f7fceeea508b98899f1c826e10ffe78
Author: Roman Gushchin <guro@fb.com>
Date:   Wed Apr 7 20:57:33 2021 -0700

    percpu: make pcpu_nr_empty_pop_pages per chunk type

    nr_empty_pop_pages is used to guarantee that there are some free
    populated pages to satisfy atomic allocations. Accounted and
    non-accounted allocations are using separate sets of chunks,
    so both need to have a surplus of empty pages.

    This commit makes pcpu_nr_empty_pop_pages and the corresponding logic
    per chunk type.

    [Dennis]
    This issue came up as I was reviewing [1] and realized I missed this.
    Simultaneously, it was reported btrfs was seeing failed atomic
    allocations in fsstress tests [2] and [3].

    [1] https://lore.kernel.org/linux-mm/20210324190626.564297-1-guro@fb.com/
    [2] https://lore.kernel.org/linux-mm/20210401185158.3275.409509F4@e16-tech.com/
    [3] https://lore.kernel.org/linux-mm/CAL3q7H5RNBjCi708GH7jnczAOe0BLnacT9C+OBgA-Dx9jhB6SQ@mail.gmail.com/

    Fixes: 3c7be18ac9a0 ("mm: memcg/percpu: account percpu memory to memory cgroups")
    Cc: stable@vger.kernel.org # 5.9+
    Signed-off-by: Roman Gushchin <guro@fb.com>
    Tested-by: Filipe Manana <fdmanana@suse.com>
    Signed-off-by: Dennis Zhou <dennis@kernel.org>

commit 632a1c209b8773cb0119fe3aada9f1db14fa357c
Author: Thomas Tai <thomas.tai@oracle.com>
Date:   Thu Apr 8 13:28:33 2021 -0400

    x86/traps: Correct exc_general_protection() and math_error() return paths

    Commit

      334872a09198 ("x86/traps: Attempt to fixup exceptions in vDSO before signaling")

    added return statements which bypass calling cond_local_irq_disable().

    According to

      ca4c6a9858c2 ("x86/traps: Make interrupt enable/disable symmetric in C code"),

    cond_local_irq_disable() is needed because the asm return code no longer
    disables interrupts. Follow the existing code as an example to use "goto
    exit" instead of "return" statement.

     [ bp: Massage commit message. ]

    Fixes: 334872a09198 ("x86/traps: Attempt to fixup exceptions in vDSO before signaling")
    Signed-off-by: Thomas Tai <thomas.tai@oracle.com>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Reviewed-by: Alexandre Chartre <alexandre.chartre@oracle.com>
    Link: https://lkml.kernel.org/r/1617902914-83245-1-git-send-email-thomas.tai@oracle.com

commit 3a62583c2853b0ab37a57dde79decea210b5fb89
Author: William Roche <william.roche@oracle.com>
Date:   Tue Apr 6 11:28:59 2021 -0400

    RAS/CEC: Correct ce_add_elem()'s returned values

    ce_add_elem() uses different return values to signal a result from
    adding an element to the collector. Commit in Fixes: broke the case
    where the element being added is not found in the array. Correct that.

     [ bp: Rewrite commit message, add kernel-doc comments. ]

    Fixes: de0e0624d86f ("RAS/CEC: Check count_threshold unconditionally")
    Signed-off-by: William Roche <william.roche@oracle.com>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: <stable@vger.kernel.org>
    Link: https://lkml.kernel.org/r/1617722939-29670-1-git-send-email-william.roche@oracle.com

commit 6d48b7912cc72275dc7c59ff961c8bac7ef66a92
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 22 12:55:25 2021 +0100

    lockdep: Address clang -Wformat warning printing for %hd

    Clang doesn't like format strings that truncate a 32-bit
    value to something shorter:

      kernel/locking/lockdep.c:709:4: error: format specifies type 'short' but the argument has type 'int' [-Werror,-Wformat]

    In this case, the warning is a slightly questionable, as it could realize
    that both class->wait_type_outer and class->wait_type_inner are in fact
    8-bit struct members, even though the result of the ?: operator becomes an
    'int'.

    However, there is really no point in printing the number as a 16-bit
    'short' rather than either an 8-bit or 32-bit number, so just change
    it to a normal %d.

    Fixes: de8f5e4f2dc1 ("lockdep: Introduce wait-type checks")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/20210322115531.3987555-1-arnd@kernel.org

commit 3a85969e9d912d5dd85362ee37b5f81266e00e77
Author: Tetsuo Handa <penguin-kernel@I-love.SAKURA.ne.jp>
Date:   Sun Mar 21 15:49:13 2021 +0900

    lockdep: Add a missing initialization hint to the "INFO: Trying to register non-static key" message

    Since this message is printed when dynamically allocated spinlocks (e.g.
    kzalloc()) are used without initialization (e.g. spin_lock_init()),
    suggest to developers to check whether initialization functions for objects
    were called, before making developers wonder what annotation is missing.

    [ mingo: Minor tweaks to the message. ]

    Signed-off-by: Tetsuo Handa <penguin-kernel@I-love.SAKURA.ne.jp>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/20210321064913.4619-1-penguin-kernel@I-love.SAKURA.ne.jp
    Signed-off-by: Ingo Molnar <mingo@kernel.org>